apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-slave
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
