apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maven-repo
  namespace: {{ .Release.Namespace }}
  annotations:
    pv.beta.kubernetes.io/gid: "10000"
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
